### ISSUE TITLE
Finally here!

### ISSUE THREAD

**Issue by TheDiamondYT1** [DragonetMC/DragonProxy-Android#1]
There is finally a DragonProxy app that is being worked on! 

@TekkitCommando I will need to host a zip file on http://files.dragonet.org containing the Java 8 library (50mb - When extracted over 100mb).

This is based on the app *MinecraftPEServer* by @fengberd.

**Comment by TekkitCommando** [comment]
@TheDiamondYT1 Are you asking permission to host a large file? or are you just informing me? xD

**Comment by TheDiamondYT1** [comment]
@TekkitCommando Im informing as i dont have access to do it myself

**Comment by TekkitCommando** [comment]
@TheDiamondYT1 Def is on Skype. Ask him for his CPanel login.

**Comment by TheDiamondYT1** [comment]
Nvm i can host it in my github repo

**Comment by DefinitlyEvil** [comment]
Github FTW!

**Comment by FaigerSYS** [comment]
1. How I can download complete app (not source)?
2. Which files I need to download here (http://files.dragonet.org/)?

**Comment by fengberd** [comment]
Ah,congratulations :D

**Comment by TheDiamondYT1** [comment]
Im not working on the app anymore, or DragonProxy in general.
